In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing


In [2]:
df = pd.read_excel('TITANIC.xlsx')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [6]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [7]:
df = df.drop(['Ticket' , 'Name', 'Cabin','PassengerId'] ,axis = 1)

In [8]:
df = df.dropna(subset = ['Embarked'] , how = 'any')

In [9]:
median_age = df.loc[:,'Age'].median()
df['Age'].fillna(value = median_age, inplace = True)

In [10]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [11]:
df.shape

(889, 8)

In [12]:
df = pd.get_dummies(df , columns = ['Sex' , 'Embarked' ,'Pclass','Parch','SibSp'] ,drop_first =True)

In [13]:
df.head()

Survived   Age     Fare  Sex_male  Embarked_Q  Embarked_S  Pclass_2  \
0         0  22.0   7.2500         1           0           1         0   
1         1  38.0  71.2833         0           0           0         0   
2         1  26.0   7.9250         0           0           1         0   
3         1  35.0  53.1000         0           0           1         0   
4         0  35.0   8.0500         1           0           1         0   

   Pclass_3  Parch_1  Parch_2  Parch_3  Parch_4  Parch_5  Parch_6  SibSp_1  \
0         1        0        0        0        0        0        0        1   
1         0        0        0        0        0        0        0        1   
2         1        0        0        0        0        0        0        0   
3         0        0        0        0        0        0        0        1   
4         1        0        0        0        0        0        0        0   

   SibSp_2  SibSp_3  SibSp_4  SibSp_5  SibSp_8  
0        0        0        0        0        0  
1        0        0        0        0        0  
2        0        0        0        0        0  
3        0        0        0        0        0  
4        0        0        0        0        0

In [14]:
x = df['Age'].values.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_age = min_max_scaler.fit_transform(x)
df['Age'] = x_age

x = df['Fare'].values.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_age = min_max_scaler.fit_transform(x)
df['Fare'] = x_age

In [15]:
df.head()

Survived       Age      Fare  Sex_male  Embarked_Q  Embarked_S  Pclass_2  \
0         0  0.271174  0.014151         1           0           1         0   
1         1  0.472229  0.139136         0           0           0         0   
2         1  0.321438  0.015469         0           0           1         0   
3         1  0.434531  0.103644         0           0           1         0   
4         0  0.434531  0.015713         1           0           1         0   

   Pclass_3  Parch_1  Parch_2  Parch_3  Parch_4  Parch_5  Parch_6  SibSp_1  \
0         1        0        0        0        0        0        0        1   
1         0        0        0        0        0        0        0        1   
2         1        0        0        0        0        0        0        0   
3         0        0        0        0        0        0        0        1   
4         1        0        0        0        0        0        0        0   

   SibSp_2  SibSp_3  SibSp_4  SibSp_5  SibSp_8  
0        0        0        0        0        0  
1        0        0        0        0        0  
2        0        0        0        0        0  
3        0        0        0        0        0  
4        0        0        0        0        0

In [20]:
X = df
y = df.pop('Survived')

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

reg = LogisticRegression()
reg.fit(X_train , y_train)
y_train_predict = reg.predict(X_train)
y_test_predict = reg.predict(X_test)

print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict))
print("Recall : " , metrics.recall_score(y_test, y_test_predict))
print("Precision : ", metrics.precision_score(y_test, y_test_predict))

Accuracy Score : 0.8089887640449438
Confusion metrics : 
 [[144  23]
 [ 28  72]]
Recall :  0.72
Precision :  0.7578947368421053


C:\Users\Abhishek Palrecha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [23]:
print(metrics.classification_report(y_test, y_test_predict))


              precision    recall  f1-score   support

           0       0.84      0.86      0.85       167
           1       0.76      0.72      0.74       100

    accuracy                           0.81       267
   macro avg       0.80      0.79      0.79       267
weighted avg       0.81      0.81      0.81       267



# PCA

In [24]:
from sklearn.decomposition import PCA
pca = PCA(random_state = 0)
pca.fit(X_train)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=0,
    svd_solver='auto', tol=0.0, whiten=False)

In [25]:
np.cumsum(pca.explained_variance_ratio_)

array([0.25660978, 0.43762921, 0.56940685, 0.68949847, 0.76618616,
       0.82834467, 0.88656461, 0.91703124, 0.93891313, 0.9534888 ,
       0.9663011 , 0.97555871, 0.98089251, 0.98586594, 0.98979186,
       0.99311116, 0.99608142, 0.99890854, 1.        ])

In [26]:
pca_final = PCA(n_components = 10, random_state = 41)

X_train_pca = pca_final.fit_transform(X_train)
X_test_pca = pca_final.transform(X_test)

# Logistic regression

In [27]:
from sklearn.linear_model import LogisticRegression

reg_pca = LogisticRegression()

reg_pca.fit(X_train_pca, y_train)
y_test_predict_lr = reg_pca.predict(X_test_pca)

C:\Users\Abhishek Palrecha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [28]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_lr))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_lr))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_lr))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_lr))

Accuracy Score : 0.7940074906367042
Confusion metrics : 
 [[139  28]
 [ 27  73]]
Recall :  0.73
Precision :  0.7227722772277227


In [29]:
print(metrics.classification_report(y_test, y_test_predict_lr))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       167
           1       0.72      0.73      0.73       100

    accuracy                           0.79       267
   macro avg       0.78      0.78      0.78       267
weighted avg       0.79      0.79      0.79       267



# KNN

In [30]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train_pca, y_train)
y_test_predict_knn = classifier.predict(X_test_pca)

In [31]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_knn))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_knn))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_knn))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_knn))

Accuracy Score : 0.7640449438202247
Confusion metrics : 
 [[138  29]
 [ 34  66]]
Recall :  0.66
Precision :  0.6947368421052632


In [32]:
print(metrics.classification_report(y_test, y_test_predict_knn))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81       167
           1       0.69      0.66      0.68       100

    accuracy                           0.76       267
   macro avg       0.75      0.74      0.75       267
weighted avg       0.76      0.76      0.76       267



# SVM

In [33]:
from sklearn.svm import SVC
classifier_svc = SVC()
classifier_svc.fit(X_train_pca , y_train)
y_test_predict_svm = classifier_svc.predict(X_test_pca)

C:\Users\Abhishek Palrecha\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [34]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_svm))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_svm))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_svm))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_svm))

Accuracy Score : 0.7902621722846442
Confusion metrics : 
 [[139  28]
 [ 28  72]]
Recall :  0.72
Precision :  0.72


In [35]:
print(metrics.classification_report(y_test, y_test_predict_knn))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81       167
           1       0.69      0.66      0.68       100

    accuracy                           0.76       267
   macro avg       0.75      0.74      0.75       267
weighted avg       0.76      0.76      0.76       267



# Decision Tree

In [36]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth = 50)
clf = clf.fit(X_train_pca , y_train)
y_test_predict_dt = clf.predict(X_test_pca)

In [37]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_dt))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_dt))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_dt))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_dt))

Accuracy Score : 0.6966292134831461
Confusion metrics : 
 [[122  45]
 [ 36  64]]
Recall :  0.64
Precision :  0.5871559633027523


In [38]:
print(metrics.classification_report(y_test, y_test_predict_dt))

              precision    recall  f1-score   support

           0       0.77      0.73      0.75       167
           1       0.59      0.64      0.61       100

    accuracy                           0.70       267
   macro avg       0.68      0.69      0.68       267
weighted avg       0.70      0.70      0.70       267



# RFE

In [39]:
df_train,df_test = train_test_split(df, train_size = 0.7, random_state = 42)

In [40]:
from sklearn.feature_selection import RFE

rfe = RFE(reg, 10)
rfe = rfe.fit(X_train, y_train)

C:\Users\Abhishek Palrecha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Abhishek Palrecha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Abhishek Palrecha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Abhishek Palrecha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Abhishek Palrecha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will 

In [41]:
temp_df = pd.DataFrame({'Columns' : X_train.columns, 'Included' : rfe.support_, 'Ranking' : rfe.ranking_})
temp_df

Columns  Included  Ranking
0          Age      True        1
1         Fare      True        1
2     Sex_male      True        1
3   Embarked_Q     False       10
4   Embarked_S     False        3
5     Pclass_2     False        2
6     Pclass_3      True        1
7      Parch_1      True        1
8      Parch_2     False        7
9      Parch_3     False        9
10     Parch_4      True        1
11     Parch_5      True        1
12     Parch_6     False        4
13     SibSp_1     False        8
14     SibSp_2     False        6
15     SibSp_3      True        1
16     SibSp_4      True        1
17     SibSp_5     False        5
18     SibSp_8      True        1

In [42]:
imp_col = X_train.columns[rfe.support_]
imp_col

Index(['Age', 'Fare', 'Sex_male', 'Pclass_3', 'Parch_1', 'Parch_4', 'Parch_5',
       'SibSp_3', 'SibSp_4', 'SibSp_8'],
      dtype='object')

In [43]:
X_train_new = df_train[imp_col]
X_train_new.head()

Age      Fare  Sex_male  Pclass_3  Parch_1  Parch_4  Parch_5  \
486  0.434531  0.175668         0         0        0        0        0   
293  0.296306  0.017274         0         1        0        0        0   
173  0.258608  0.015469         1         1        0        0        0   
450  0.447097  0.054164         1         0        0        0        0   
361  0.359135  0.054107         1         0        0        0        0   

     SibSp_3  SibSp_4  SibSp_8  
486        0        0        0  
293        0        0        0  
173        0        0        0  
450        0        0        0  
361        0        0        0

In [44]:
regressor = LogisticRegression()
regressor.fit(X_train_new, y_train)
y_train_predict_new = regressor.predict(X_train_new)

X_test_new = df_test[imp_col]
y_test_predict_new = regressor.predict(X_test_new)

C:\Users\Abhishek Palrecha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [45]:
temp_df_new = pd.DataFrame({'Actual' : y_test , 'Predicted' : y_test_predict_new})
temp_df_new

Actual  Predicted
281       0          0
435       1          1
39        1          1
418       0          0
585       1          1
804       1          0
343       0          0
836       0          0
581       1          1
537       1          1
791       0          0
142       1          1
631       0          0
73        0          0
713       0          0
508       0          0
544       0          0
531       0          0
817       0          0
738       0          0
71        0          1
166       1          1
197       0          0
295       0          0
589       0          0
30        0          0
292       0          0
303       1          1
602       0          0
619       0          0
..      ...        ...
329       1          1
586       0          0
686       0          0
432       1          1
522       0          0
716       1          1
353       0          0
483       1          0
659       0          0
653       1          1
213       0          0
449       1          0
80        0          0
149       0          0
837       0          0
60        0          0
540       1          1
877       0          0
799       0          1
378       0          0
327       1          1
134       0          0
463       0          0
543       1          0
465       0          0
454       0          0
632       1          0
693       0          0
741       0          0
430       1          0

[267 rows x 2 columns]

In [46]:
print("Accuracy Score :",metrics.accuracy_score(y_test , y_test_predict_new))
print("Confusion metrics : \n", metrics.confusion_matrix(y_test,y_test_predict_new))
print("Recall : " , metrics.recall_score(y_test, y_test_predict_new))
print("Precision : ", metrics.precision_score(y_test, y_test_predict_new))

Accuracy Score : 0.8052434456928839
Confusion metrics : 
 [[144  23]
 [ 29  71]]
Recall :  0.71
Precision :  0.7553191489361702


In [47]:
print(metrics.classification_report(y_test, y_test_predict_new))

              precision    recall  f1-score   support

           0       0.83      0.86      0.85       167
           1       0.76      0.71      0.73       100

    accuracy                           0.81       267
   macro avg       0.79      0.79      0.79       267
weighted avg       0.80      0.81      0.80       267



# This is the best model we have of accuracy around 80%